/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * USBRobotControllerApplication.java
 *
 * Created on Jan 3, 2012, 9:19:17 PM
 */
package ui;

import commonutilities.swing.ComponentPosition;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import ui.installation.JinputInstallationFrame;
import ui.installation.RxtxInstallationFrame;

/**
 *
 * @author Parham
 */
public class USBRobotControllerApplication extends javax.swing.JFrame {

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        if (args.length == 0){
            java.awt.EventQueue.invokeLater(new Runnable() {
                @Override
                public void run() {
                    setLookAndFeel();
                    //Center the frame
                    USBRobotControllerApplication controller = new USBRobotControllerApplication();
                    ComponentPosition.centerFrame(controller);
                    controller.setVisible(true);
                }
            });
        } else if (args.length == 1){
            if (args[0].equals("rxtx")){
                java.awt.EventQueue.invokeLater(new Runnable() {
                    @Override
                    public void run() {
                        setLookAndFeel();
                        //Center the frame
                        RxtxInstallationFrame dialog = new RxtxInstallationFrame();
                        ComponentPosition.centerFrame(dialog);
                        dialog.setVisible(true);
                    }
                });
            } else if (args[0].equals("jinput")){
                java.awt.EventQueue.invokeLater(new Runnable() {
                    @Override
                    public void run() {
                        setLookAndFeel();
                        //Center the frame
                        JinputInstallationFrame dialog = new JinputInstallationFrame();
                        ComponentPosition.centerFrame(dialog);
                        dialog.setVisible(true);
                    }
                });
            }
        }
    }

    /** Creates new form USBRobotControllerApplication */
    public USBRobotControllerApplication() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

    private static void setLookAndFeel(){
        //Set the look and feel to Nimbus
        try {
            UIManager.setLookAndFeel("com.sun.java.swing.plaf.nimbus.NimbusLookAndFeel");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(USBRobotControllerApplication.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            Logger.getLogger(USBRobotControllerApplication.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(USBRobotControllerApplication.class.getName()).log(Level.SEVERE, null, ex);
        } catch (UnsupportedLookAndFeelException ex) {
            Logger.getLogger(USBRobotControllerApplication.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

}
