/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * USBRobotControllerApplication.java
 *
 * Created on Jan 3, 2012, 9:19:17 PM
 */
package ui;

import ui.characterize.CharacterizeDialog;
import commonutilities.swing.ComponentPosition;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import net.java.games.input.Version;
import ui.installation.JinputInstallationFrame;
import ui.installation.RxtxInstallationFrame;

/**
 *
 * @author Parham
 */
public class USBRobotControllerApplication extends javax.swing.JFrame {

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        if (args.length == 0){
            java.awt.EventQueue.invokeLater(new Runnable() {
                @Override
                public void run() {
                    setLookAndFeel();
                    //Center the frame
                    USBRobotControllerApplication controller = new USBRobotControllerApplication();
                    ComponentPosition.centerFrame(controller);
                    controller.setVisible(true);
                }
            });
        } else if (args.length == 1){
            if (args[0].equals("rxtx")){
                java.awt.EventQueue.invokeLater(new Runnable() {
                    @Override
                    public void run() {
                        setLookAndFeel();
                        //Center the frame
                        RxtxInstallationFrame dialog = new RxtxInstallationFrame();
                        ComponentPosition.centerFrame(dialog);
                        dialog.setVisible(true);
                    }
                });
            } else if (args[0].equals("jinput")){
                java.awt.EventQueue.invokeLater(new Runnable() {
                    @Override
                    public void run() {
                        setLookAndFeel();
                        //Center the frame
                        JinputInstallationFrame dialog = new JinputInstallationFrame();
                        ComponentPosition.centerFrame(dialog);
                        dialog.setVisible(true);
                    }
                });
            }
        }
    }

    /** Creates new form USBRobotControllerApplication */
    public USBRobotControllerApplication() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mControllerLabel = new javax.swing.JLabel();
        mMenuBar = new javax.swing.JMenuBar();
        mFileMenu = new javax.swing.JMenu();
        mExitMenuItem = new javax.swing.JMenuItem();
        mEditMenu = new javax.swing.JMenu();
        mSelectControllerMenuItem = new javax.swing.JMenuItem();
        mCharacterizeMenuItem = new javax.swing.JMenuItem();
        mJinputVersionMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Robot Controller");

        mControllerLabel.setText("Controller: Not Selected");

        mFileMenu.setText("File");

        mExitMenuItem.setText("Exit");
        mExitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mExitMenuItemActionPerformed(evt);
            }
        });
        mFileMenu.add(mExitMenuItem);

        mMenuBar.add(mFileMenu);

        mEditMenu.setText("Edit");

        mSelectControllerMenuItem.setText("Select Controller");
        mEditMenu.add(mSelectControllerMenuItem);

        mCharacterizeMenuItem.setText("Characterize Controller...");
        mCharacterizeMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mCharacterizeMenuItemActionPerformed(evt);
            }
        });
        mEditMenu.add(mCharacterizeMenuItem);

        mJinputVersionMenuItem.setText("Show JInput Version");
        mJinputVersionMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mJinputVersionMenuItemActionPerformed(evt);
            }
        });
        mEditMenu.add(mJinputVersionMenuItem);

        mMenuBar.add(mEditMenu);

        setJMenuBar(mMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mControllerLabel)
                .addContainerGap(275, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mControllerLabel)
                .addContainerGap(254, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mExitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mExitMenuItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_mExitMenuItemActionPerformed


    private void mJinputVersionMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mJinputVersionMenuItemActionPerformed
        JOptionPane.showMessageDialog(this, "JInput version: " + Version.getVersion(),  "JInput Version", JOptionPane.PLAIN_MESSAGE);
    }//GEN-LAST:event_mJinputVersionMenuItemActionPerformed

    private void mCharacterizeMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mCharacterizeMenuItemActionPerformed
        CharacterizeDialog dialog = new CharacterizeDialog(this, true);
        ComponentPosition.centerFrame(dialog);
        dialog.setVisible(true);
    }//GEN-LAST:event_mCharacterizeMenuItemActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem mCharacterizeMenuItem;
    private javax.swing.JLabel mControllerLabel;
    private javax.swing.JMenu mEditMenu;
    private javax.swing.JMenuItem mExitMenuItem;
    private javax.swing.JMenu mFileMenu;
    private javax.swing.JMenuItem mJinputVersionMenuItem;
    private javax.swing.JMenuBar mMenuBar;
    private javax.swing.JMenuItem mSelectControllerMenuItem;
    // End of variables declaration//GEN-END:variables

    private static void setLookAndFeel(){
        //Set the look and feel to Nimbus
        try {
            UIManager.setLookAndFeel("com.sun.java.swing.plaf.nimbus.NimbusLookAndFeel");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(USBRobotControllerApplication.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            Logger.getLogger(USBRobotControllerApplication.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(USBRobotControllerApplication.class.getName()).log(Level.SEVERE, null, ex);
        } catch (UnsupportedLookAndFeelException ex) {
            Logger.getLogger(USBRobotControllerApplication.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

}
