/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * USBRobotControllerApplication.java
 *
 * Created on Jan 3, 2012, 9:19:17 PM
 */
package ui;

import commonutilities.swing.ComponentPosition;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import net.java.games.input.Version;
import ui.installation.JinputInstallationFrame;
import ui.installation.RxtxInstallationFrame;

/**
 *
 * @author Parham
 */
public class USBRobotControllerApplication extends javax.swing.JFrame {

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        if (args.length == 0){
            java.awt.EventQueue.invokeLater(new Runnable() {
                @Override
                public void run() {
                    setLookAndFeel();
                    //Center the frame
                    USBRobotControllerApplication controller = new USBRobotControllerApplication();
                    ComponentPosition.centerFrame(controller);
                    controller.setVisible(true);
                }
            });
        } else if (args.length == 1){
            if (args[0].equals("rxtx")){
                java.awt.EventQueue.invokeLater(new Runnable() {
                    @Override
                    public void run() {
                        setLookAndFeel();
                        //Center the frame
                        RxtxInstallationFrame dialog = new RxtxInstallationFrame();
                        ComponentPosition.centerFrame(dialog);
                        dialog.setVisible(true);
                    }
                });
            } else if (args[0].equals("jinput")){
                java.awt.EventQueue.invokeLater(new Runnable() {
                    @Override
                    public void run() {
                        setLookAndFeel();
                        //Center the frame
                        JinputInstallationFrame dialog = new JinputInstallationFrame();
                        ComponentPosition.centerFrame(dialog);
                        dialog.setVisible(true);
                    }
                });
            }
        }
    }

    /** Creates new form USBRobotControllerApplication */
    public USBRobotControllerApplication() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        exitMenuItem = new javax.swing.JMenuItem();
        characterizeMenuItem = new javax.swing.JMenu();
        selectControllerMenuItem = new javax.swing.JMenuItem();
        jinputVersionMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Robot Controller");

        jLabel1.setText("Controller: Not Selected");

        fileMenu.setText("File");

        exitMenuItem.setText("Exit");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(exitMenuItem);

        menuBar.add(fileMenu);

        characterizeMenuItem.setText("Edit");

        selectControllerMenuItem.setText("Select Controller");
        characterizeMenuItem.add(selectControllerMenuItem);

        jinputVersionMenuItem.setText("Show JInput Version");
        jinputVersionMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jinputVersionMenuItemActionPerformed(evt);
            }
        });
        editMenu.add(jinputVersionMenuItem);

        menuBar.add(editMenu);
        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(275, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(254, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitMenuItemActionPerformed


    private void jinputVersionMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jinputVersionMenuItemActionPerformed
        JOptionPane.showMessageDialog(this, "JInput version: " + Version.getVersion(),  "JInput Version", JOptionPane.PLAIN_MESSAGE);
    }//GEN-LAST:event_jinputVersionMenuItemActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu characterizeMenuItem;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu editMenu;
    private javax.swing.JMenuItem jinputVersionMenuItem;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem selectControllerMenuItem;
    // End of variables declaration//GEN-END:variables

    private static void setLookAndFeel(){
        //Set the look and feel to Nimbus
        try {
            UIManager.setLookAndFeel("com.sun.java.swing.plaf.nimbus.NimbusLookAndFeel");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(USBRobotControllerApplication.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            Logger.getLogger(USBRobotControllerApplication.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(USBRobotControllerApplication.class.getName()).log(Level.SEVERE, null, ex);
        } catch (UnsupportedLookAndFeelException ex) {
            Logger.getLogger(USBRobotControllerApplication.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

}
