/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package util.jinput;

import commonutilities.swing.ComponentPosition;

/**
 *
 * @author Parham
 */
public class MissingDllDialog extends javax.swing.JDialog {

    /**
     * Creates new form MissingDllDialog
     */
    public MissingDllDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mErrorLabel = new javax.swing.JLabel();
        mExitButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("No USB Gamepad");

        mErrorLabel.setText("<html>No USB gamepad was found on your system. There are two possible causes:<br><br>\n1 - A system installed gamepad is not plugged in to the USB port.<br>\n2 - Jinput .dll files are missing.<br><br>\nPlease plug in an installed gamepad or check your Java configuration by running <b>java -jar USBRobotGamepadApp.java jinput</b> on the command line to install files.</html>");

        mExitButton.setText("Exit");
        mExitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mExitButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(mExitButton))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(mErrorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mErrorLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mExitButton)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mExitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mExitButtonActionPerformed
        System.exit(1);
    }//GEN-LAST:event_mExitButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel mErrorLabel;
    private javax.swing.JButton mExitButton;
    // End of variables declaration//GEN-END:variables

    @Override
    public void setVisible(boolean b){
        ComponentPosition.centerFrame(this);
        super.setVisible(b);
    }

}
